services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file: 
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    env_file: 
      - ./backend/.env 
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: easytrip
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.local
