version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - easytrip_network

  db:
    image: mysql:latest
    restart: always
    env_file: 
      - ./backend/.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: easytrip
    ports:
      - "3307:3306"
    volumes:
      - ./easyTripDb.sql:/docker-entrypoint-initdb.d/easyTripDb.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - easytrip_network

  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.local
    networks:
      - easytrip_network

networks:
  easytrip_network:
    driver: bridge
